---
# Resourceの定義
resources:
# Git Resourceの定義
- name: hello
  type: git
  source:
    uri: https://github.com/ababup1192/hello-concourse.git
- name: result
  type: git
  source:
    uri: git@gist.github.com:4054dbbf37296123c02c3ef709a154f2.git
    private_key: {{github-private-key}}
    branch: master

# Jobの定義
jobs:
- name: job-hello
  public: true # UI上でJobの結果をログイン不要で公開するかどうか
  plan:
  - get: hello
    trigger: true # Resourceに変更があれば自動でジョブを実行するかどうか
  - get: result
  - task: run-hello
    file: hello/hello.yml
  - task: commit-log
    file: hello/commit-log.yml
  - put: result
    params:
      repository: updated-result
- name: job-show-result
  public: true
  plan:
  - get: hello
  - get: result
    trigger: true
    passed: [ job-hello ]
  - task: show-result
    file: hello/show-result.yml
